# Copyright (c) 2015-2018 Mark Hamilton, All rights reserved
"""
Django settings for djconfig project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

print "MARK: end", STATIC_ROOT

