# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpooldb', '0002_auto_20180429_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HV',
            new_name='Host',
        ),
    ]
