# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-12 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testpooldb', '0004_auto_20180729_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('template_name', models.CharField(max_length=128)),
                ('resource_max', models.IntegerField(default=1)),
                ('expiration', models.IntegerField(default=600)),
                ('status', models.IntegerField(default=1)),
                ('action', models.CharField(default=b'none', max_length=36)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpooldb.Host')),
            ],
        ),
        migrations.CreateModel(
            name='PoolKVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpooldb.KVP')),
                ('pool', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='testpooldb.Pool')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='host',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='kvps',
        ),
        migrations.RemoveField(
            model_name='profilekvp',
            name='kvp',
        ),
        migrations.RemoveField(
            model_name='profilekvp',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='traceback',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileKVP',
        ),
        migrations.AddField(
            model_name='pool',
            name='kvps',
            field=models.ManyToManyField(through='testpooldb.PoolKVP', to='testpooldb.KVP'),
        ),
        migrations.AddField(
            model_name='resource',
            name='pool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testpooldb.Pool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceback',
            name='pool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testpooldb.Pool'),
            preserve_default=False,
        ),
    ]
